import { DocumentPage } from './Document/DocumentPage';
import { EditorPage } from './Editor/EditorPage';
import { ErrorPage } from './Error/ErrorPage';
import { HomePage } from './Home/HomePage';
import { About } from './Abouts/About';
import { Privacy } from './Abouts/Privacy';
import { SettingsPage } from './Setting/SettingsPage';
import { CategoriesPage } from './Categories/CategoriesPage';
import { DocumentsPage } from './Documents/DocumentsPage';
export {HomePage, DocumentPage, EditorPage, ErrorPage, About, Privacy, SettingsPage, CategoriesPage, DocumentsPage};
